### ISSUE TITLE
Error during migrations in VS2015 package manager

### ISSUE THREAD

**Issue by punkouter2021** [chsakell/dotnetcore-entityframework-api#1]
Navigated to the API directory and ran the migration command. Any idea ? 

dotnet : Your target project 'scheduler.API' doesn't match your migrations assembly 'Scheduler.API'. Either change your target project or change your migrations assembly.

**Comment by chsakell** [comment]
@punkouter Have you set the **Migration Assembly** in the _Startup.ConfigureServices_ properly? The '**s**cheduler.API' is different from '**S**cheduler.API'.

``` csharp
services.AddDbContext<SchedulerContext>(options =>
        options.UseSqlServer(Configuration["Data:SchedulerConnection:ConnectionString"],
        b => b.MigrationsAssembly("Scheduler.API")));
```

I have just run the following command as described on the [post](http://wp.me/p3mRWu-18G) and it worked fine.

```
dotnet ef migrations add "initial"
```

![init migrations](https://chsakell.files.wordpress.com/2016/06/dotnet-core-api-08.png)

**Comment by punkouter2021** [comment]
I have to change the capitalization. 

 b => b.MigrationsAssembly("scheduler.api")));

**Comment by punkouter2021** [comment]
Cant get the client to work. Where in the client js does it reference what url/port to use ?

**Comment by chsakell** [comment]
Let's close this issue here. For instructions on how to run the client read the associated  [readme.md](https://github.com/chsakell/angular2-features/blob/master/README.md) file or the [post](http://wp.me/p3mRWu-199).
