### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by dali-gharbi** [chsakell/dotnetcore-entityframework-api#3]
"Microsoft.NETCore.App": {
      "version": "1.1.0",
      "type": "platform"
    },

Severity	Code	Description	Project	File	Line	Suppression State Error	
MSB4019	The imported project "C:\ProgramFiles\dotnet\sdk\1.0.1\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.	Scheduler.API	C:\Users\<name>\Documents\Visual Studio 2015\Projects\dotnetcore-entityframework-api-master\Scheduler.API\Scheduler.API.xproj	8

**Comment by chsakell** [comment]
There is a AppVeyor build status indicator _(badge)_ that shows the current build status of the project. 
[![Build status](https://ci.appveyor.com/api/projects/status/github/chsakell/dotnetcore-entityframework-api?branch=master&svg=true)](https://ci.appveyor.com/project/chsakell/dotnetcore-entityframework-api/branch/master)
You will found the badge in the readme file as well.
