### ISSUE TITLE
Getting error in second command execution

### ISSUE THREAD

**Issue by munish29sharma** [chsakell/dotnetcore-entityframework-api#5]
While running second command "dotnet ef database update"

getting error "KeyWord nor supported: Userid"
![untitled](https://cloud.githubusercontent.com/assets/28429974/26062397/51cb28b8-39a8-11e7-8119-c8bb92a1d7b8.png)

**Comment by chsakell** [comment]
It seems that your connection string is wrong. Can you provide it? In case you need to pass a user id, you should use "User Id", not "userid".
Check [this](https://www.connectionstrings.com/sql-server/) link for more examples.

**Comment by chsakell** [comment]
EF commands have changed as described [here](https://github.com/chsakell/dotnetcore-entityframework-api/blob/master/README.md).
